apiVersion: apps/v1
kind: Deployment
metadata:
  name: threads-image
spec:
  replicas: 0
  selector:
    matchLabels:
      app: threads-image
  template:
    metadata:
      labels:
        app: threads-image
    spec:
      containers:
      - name: threads-image
        image: 912643663034.dkr.ecr.ap-southeast-1.amazonaws.com/threads-image-dapi:202306261526
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        livenessProbe:
          httpGet:
            path: /threads/actuator/health/liveness
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /threads/actuator/health/readiness
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /threads/actuator/health/liveness
            port: 8082
          failureThreshold: 30
          periodSeconds: 10
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: threads-image-svc
  labels:
    app: threads-image
spec:
  selector:
    app: threads-image
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: svc-port