FROM base:1.0.0
MAINTAINER wood
VOLUME /tmp
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
RUN mkdir -p /var/lib/crash
ENV ARTIFACT=crash
COPY ././crash/lib /var/lib/crash/lib
COPY ././common-libs /var/lib/crash/common-libs
COPY ././springProfiles /var/lib/crash/springProfiles
COPY ././crash/*.jar /$ARTIFACT.jar
ENV JAVA_OPTS="\
-Xms2048m \
-Xmx2048m \
-Xss512K \
"
EXPOSE 8084
ENTRYPOINT java -Dloader.path=/var/lib/crash/lib,/var/lib/crash/common-libs -jar /$ARTIFACT.jar --spring.config.location=/var/lib/crash/springProfiles/test/application-crash.yaml
