FROM base:1.0.0
MAINTAINER wood
VOLUME /tmp
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
RUN mkdir -p /var/lib/threads
ENV ARTIFACT=threads
COPY ././threads/lib /var/lib/threads/lib
COPY ././common-libs /var/lib/threads/common-libs
COPY ././springProfiles /var/lib/threads/springProfiles
COPY ././threads/*.jar /$ARTIFACT.jar
ENV JAVA_OPTS="\
-Xms2048m \
-Xmx2048m \
-Xss512K \
"
EXPOSE 8082
ENTRYPOINT java -Dloader.path=/var/lib/threads/lib,/var/lib/threads/common-libs -jar /$ARTIFACT.jar --spring.config.location=/var/lib/threads/springProfiles/test/application-threads.yaml
